### ISSUE TITLE
Update Android wallet to understand v2 final

### ISSUE THREAD

**Issue by kimdhamilton** [blockchain-certificates/wallet-android#1]
The current version of Blockcerts is v2-alpha. V2 (the final version) is now available, which contains the feedback from OBI.

We should continue to support v2-alpha as well as v2. The changes affect both the certificate and the issuer schema. The changes are described below:

### Recipient profile moved up 1 level

`recipientProfile` moved up 1 level in V2. In other words:

V2-alpha:
```
{
    "recipient": {
        "recipientProfile": {
            ...
        }
    }
}
```

V2:
```
{
    "recipient": {
    },
    "recipientProfile": {
         ...
    }
}
```

### Verification `creator` field changed to `publicKey`

V2-alpha:
```
{
    "verification": {
        "creator": {
             ....
        }
    }
}
```

V2:
```
{
    "verification": {
        "publicKey": {
             ....
        }
    }
}
```

### Use canonical JSON-LD contexts

This is relevant if the viewer/verifier is caching the JSON-LD context. In V2 the expected JSON-LD contexts are:
- https://w3id.org/openbadges/v2
- https://w3id.org/blockcerts/v2

## Issuer schema changes

- `publicKeys` -> `publicKey`
- `publicKey`  -> `id`

Example:

V2-alpha:
```
{
    "publicKeys": [
        "publicKey": {
            ...
        }  
    ]
}
```
V2:
```
{
    "publicKey": [
        "id": {
            ...
        }  
    ]
}
```

A sample v2 testnet certificate is here: https://github.com/blockchain-certificates/cert-verifier-js/blob/master/tests/data/sample_cert-valid-2.0.json

**Comment by bolot** [comment]
Latest master should fix this.
