### ISSUE TITLE
This repository is missing a license file

### ISSUE THREAD

**Issue by 1l2p** [blockchain-certificates/wallet-android#26]
Similar to the other repositories, it would be helpful to add a license file that explicitly states that the source code is available under the MIT license. It is not clear how others would be able to build on / extend the code otherwise.

**Comment by 1l2p** [comment]
Hey @kimdhamilton - any update on this? Since I am not the owner of the source code in this repository, I can't add the license file myself.

**Comment by kimdhamilton** [comment]
done!
