### ISSUE TITLE
Adding Italian language support and translation

### ISSUE THREAD

**Issue by dariomas** [blockchain-certificates/wallet-android#29]

**Comment by dariomas** [comment]
The PR #30 https://github.com/blockchain-certificates/wallet-android/pull/30 needs updated "about-passphrase" and "privacy policy" links to their translated versions:
https://github.com/blockchain-certificates/blockchain-certificates.github.io/pull/40
found by the string resources:
    <string name="settings_privacy_policy_endpoint">https://www.blockcerts.org/it/mobile-privacy</string>
    <string name="about_passphrases_endpoint">https://www.blockcerts.org/it/about-passphrase</string>

**Comment by raiseandfall** [comment]
@dariomas I merged your [PR](https://github.com/blockchain-certificates/blockchain-certificates.github.io/pull/40), thanks!

**Comment by dariomas** [comment]
Thanks @raiseandfall 
please check and merge the PR #30
