### ISSUE TITLE
Calculate Issuer grid item sizes

### ISSUE THREAD

**Issue by downie** [blockchain-certificates/wallet-android#3]
Right now, the issuer tiles are a fixed size. This is good enough, but not great. What we'd *really* like to do is:
* Determine the device's narrowest width
* Create 2 columns in portrait mode with 8dp gutters & padding between the columns
* Maintain this size when the device is rotated (with minimum 8dp padding around each tile)

**Comment by kimdhamilton** [comment]
No longer needed due to Small Planet fixes.
