### ISSUE TITLE
Fetch Remote Hash Fail: Could not confirm the transaction

### ISSUE THREAD

**Issue by Skyquek** [blockchain-certificates/wallet-android#43]
The verification stuck at Fetch Remote hash: Could not confirm the transaction. It seems to be working well with blockcert official web. Strange enough that before this everything is good, just recently not working.

**Comment by AnthonyRonning** [comment]
Thanks for reporting. There was an issue with an API being used by cert-verifier-js (which our mobile apps use) which is affecting various components. An updated was made shortly after discovering that and has been applied to blockcerts. 

A branch has been made with a candidate update to the mobile apps that should work, but futher testing and then app distribution to the stores needs to be made. This is only affecting bitcoin certificates atm. 

https://github.com/blockchain-certificates/wallet-android/tree/mobile-build-cvjs-update

**Comment by Skyquek** [comment]
Thanks for the info. Hope the issues will be resolved soon.

**Comment by AnthonyRonning** [comment]
Build has been pushed to the google play store and should be available. 3.1.2. 

Wait up to 12 - 24 hours if it's not available for you yet.
