### ISSUE TITLE
Update testnet certificate detection to look at issuer address

### ISSUE THREAD

**Issue by downie** [blockchain-certificates/wallet-android#5]
With improvements to the v2 certificate standard, you can now issue testnet certificates to main net addresses. This flexibility is great in testing, but verification in the Android app hasn't been updated to reflect this new constraint. When presented with one of these certificates, it (incorrectly) thinks it's a main net certificate and tries to verify it. 

While the verification still (correctly) fails, it doesn't fail with the "This is a testnet certificate" message. The verification code should be updated to inspect the address of the issuer, instead of the recipient, in order to determine if it's a testnet certificate.

Also, this is the current heuristic. Future versions of the certificate standard will be more explicit about the intended chain & network a certificate is meant to be verified on.

**Comment by kimdhamilton** [comment]
No longer needed due to Small Planet fixes.
