### ISSUE TITLE
Images in certificates display with incorrect orientation.

### ISSUE THREAD

**Issue by downie** [blockchain-certificates/wallet-android#8]
Repro steps:
1. Import the example certificate below into the Android app.
2. Observe the orientation of the embedded image.

Expected: It should render as a portrait image, with all the words reading normally.
Actual: It renders as a landscape image, and the letters spell out vertically.

Example certificate: https://stagecerts.adangutierrez.com/certificate/b5467ae2c6fc5511b6e298e958274b09

Android screenshot:
![30339293-2a97a568-97b4-11e7-95aa-fe4821d5cf36](https://user-images.githubusercontent.com/547866/30398420-81891e54-988d-11e7-8f3b-229bda5a2c82.png)

Source image: 
![30394297-5089cd1c-9888-11e7-9ef8-74b7684ce1d5](https://user-images.githubusercontent.com/547866/30398341-43c35bb6-988d-11e7-87cf-4a1970fc8c99.jpg)

**Comment by hevyw8** [comment]
The web component orients this image the same as android. the file originated from an iphone, so presumably the iOS wallet is reading the orientation metadata, where as the web component and thus the android wallet both orient the image sideways. perhaps we should in that case move this issue to the web component? Not sure...

**Comment by downie** [comment]
Agreed. It seems that:
1. The intended orientation when you took the picture was to have the text be readable normally.
2. The web component is actually where the core of this bug is.

**Comment by kimdhamilton** [comment]
No longer needed due to Small Planet fixes.
